<?php
$title = 'Adicionar nova pessoa';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$person = $form->get('name');
$person->setAttribute('class', 'form-control');
$person->setAttribute('placeholder', 'Pessoa nome');


// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('universa/default', ['controller' => 'person', 'action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($person) ?>
    <?= $this->formElement($person) ?>
    <?= $this->formElementErrors()->render($person, ['class' => 'help-block']) ?>
</div>

<div class="col-12">

<?= $this->formSubmit($submit) ?>

<a class="btn btn-secondary" href="<?= $this->url('universa/default', ['controller' => 'person', 'action' => 'index']) ?>">Voltar</a>

</div>
<?php
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>


