<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete Pessoa';
$url = $this->url('universa/default', ['controller' => 'person', 'action' => 'delete', 'id' => $id]);

$this->headTitle($title);
$person = $form->get('name');
$person->setAttribute('class', 'form-control');
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Tem certeza que deseja excluir
    "<?= $this->escapeHtml($form->get('name')->getValue()) ?>" ?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Sim" />
    <input type="submit" class="btn btn-success" name="del" value="Não" />
</div>
</form>